parameters:
    kunstmaan_dashboard.widget.googleanalytics.controller: Kunstmaan\DashboardBundle\Controller\GoogleAnalyticsController

services:
    kunstmaan_dashboard.manager.widgets:
        class: Kunstmaan\DashboardBundle\Manager\WidgetManager
        public: true

    kunstmaan_dashboard.widget.googleanalytics:
        class: Kunstmaan\DashboardBundle\Widget\DashboardWidget
        arguments: ['kuma:dashboard:widget:googleanalytics:data:collect', '%kunstmaan_dashboard.widget.googleanalytics.controller%']
        tags:
            - { name: kunstmaan_dashboard.widget, priority: 1 }

    # google client
    kunstmaan_dashboard.googleclient:
        class: Google_Client
        calls:
          - [ 'setApplicationName', [ '%kunstmaan_dashboard.google_analytics.api.app_name%' ] ]
          - [ 'setClientId', [ '%kunstmaan_dashboard.google_analytics.api.client_id%' ] ]
          - [ 'setClientSecret', [ '%kunstmaan_dashboard.google_analytics.api.client_secret%' ] ]
          - [ 'setDeveloperKey', [ '%kunstmaan_dashboard.google_analytics.api.dev_key%' ] ]
          - [ 'setScopes', [ 'https://www.googleapis.com/auth/analytics.readonly' ] ]
          - [ 'setUseObjects', [ true ] ]

    # client helper
    kunstmaan_dashboard.helper.google.client:
        class: 'Kunstmaan\DashboardBundle\Helper\Google\ClientHelper'
        arguments: ['@kunstmaan_dashboard.googleclient', '@router', 'KunstmaanDashboardBundle_setToken']
        public: true

    # service helper
    kunstmaan_dashboard.helper.google.analytics.service:
        class: 'Kunstmaan\DashboardBundle\Helper\Google\Analytics\ServiceHelper'
        arguments: ['@kunstmaan_dashboard.helper.google.client']
        public: true

    # config helper
    kunstmaan_dashboard.helper.google.analytics.config:
        class: 'Kunstmaan\DashboardBundle\Helper\Google\Analytics\ConfigHelper'
        arguments: ['@kunstmaan_dashboard.helper.google.analytics.service', '@doctrine.orm.entity_manager']
        public: true

    # query helper
    kunstmaan_dashboard.helper.google.analytics.query:
        class: 'Kunstmaan\DashboardBundle\Helper\Google\Analytics\QueryHelper'
        arguments: ['@kunstmaan_dashboard.helper.google.analytics.service', '@kunstmaan_dashboard.helper.google.analytics.config']
        public: true

    Kunstmaan\DashboardBundle\Controller\DashboardController:
        arguments: ['@kunstmaan_dashboard.manager.widgets']
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\DashboardBundle\Controller\GoogleAnalyticsAJAXController:
        arguments: [ '@kernel', '@kunstmaan_dashboard.helper.google.analytics.config', '@doctrine.orm.entity_manager', '@translator' ]
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\DashboardBundle\Controller\GoogleAnalyticsController:
        arguments: [ '@kunstmaan_dashboard.helper.google.analytics.config', '@kunstmaan_dashboard.helper.google.client', '@doctrine.orm.entity_manager']
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
