parameters:
    kunstmaan_dashboard.widget.googleanalytics.command: Kunstmaan\DashboardBundle\Command\GoogleAnalyticsCommand
    kunstmaan_dashboard.widget.googleanalytics.controller: Kunstmaan\DashboardBundle\Controller\GoogleAnalyticsController
    kunstmaan_dashboard.googleclient.class: 'Google_Client'
    kunstmaan_dashboard.googleclienthelper.class: 'Kunstmaan\DashboardBundle\Helper\GoogleClientHelper'
    google.api.app_name: 'Kuma Analytics Dashboard'

services:
    kunstmaan_dashboard.manager.widgets:
        class: Kunstmaan\DashboardBundle\Manager\WidgetManager

    kunstmaan_dashboard.widget.googleanalytics:
        class: Kunstmaan\DashboardBundle\Widget\DashboardWidget
        arguments: [%kunstmaan_dashboard.widget.googleanalytics.command%, %kunstmaan_dashboard.widget.googleanalytics.controller%, '@service_container']
        tags:
            - { name: kunstmaan_dashboard.widget, priority: 1 }

    kunstmaan_dashboard.googleclient:
        class: "%kunstmaan_dashboard.googleclient.class%"
        calls:
          - [ "setApplicationName", [ "%google.api.app_name%" ] ]
          - [ "setClientId", [ "%google.api.client_id%" ] ]
          - [ "setClientSecret", [ "%google.api.client_secret%" ] ]
          - [ "setDeveloperKey", [ "%google.api.dev_key%" ] ]
          - [ "setScopes", [ 'https://www.googleapis.com/auth/analytics.readonly' ] ]
          - [ "setUseObjects", [ true ] ]

    kunstmaan_dashboard.googleclienthelper:
        class: "%kunstmaan_dashboard.googleclienthelper.class%"
        arguments: ["@kunstmaan_dashboard.googleclient", "@doctrine.orm.entity_manager"]
        calls:
          - [ "setRedirectUri", [ "@router", "KunstmaanDashboardBundle_setToken" ] ]

    kunstmaan_dashboard.googleanalyticshelper:
        class: "Kunstmaan\DashboardBundle\Helper\GoogleAnalyticsHelper"
